runtime: python27
api_version: 1
threadsafe: true

skip_files:
- src/
- logs/
- .git/
- .gitignore

handlers:

- url: /(.*\.(png|jpg|css|js|html))$
  secure: always
  static_files: build/\1
  upload: build/(.*)

- url: /
  secure: always
  static_files: build/verein.html
  upload: build/verein.html

# Match /<name> urls to top-level html files
- url: /(.*)$
  secure: always
  static_files: build/\1.html
  upload: build/.*\.html
