# NOTE(sven): We're cheeky for deployment. By setting up the handlers below we
# can copy basic nginx behaviour using Google App Engine. This gives us the
# advantage of managed deployments with SSL certificates, basic cookie-free
# analytics, hosting etc.

runtime: python27
api_version: 1
threadsafe: true

skip_files:
- src/
- logs/
- .git/
- .gitignore

handlers:

# All supported file types
- url: /(.*\.(png|jpg|css|js|html|woff2))$
  secure: always
  static_files: build/\1
  upload: build/(.*)

# Index
- url: /
  secure: always
  static_files: build/verein.html
  upload: build/verein.html

# Match /<name> urls to top-level html files
- url: /(.*)$
  secure: always
  static_files: build/\1.html
  upload: build/.*\.html
