runtime: python27
api_version: 1
threadsafe: true

skip_files:
- src/
- logs/
- .git/
- .gitignore

handlers:
- url: /
  secure: always
  static_files: build/verein.html
  upload: build/verein.html

- url: /(.*)
  secure: always
  static_files: build/\1
  upload: build/(.*)
